# Generated by Django 5.2.6 on 2026-02-27 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField()),
                ('formality_range', models.CharField(help_text="Наприклад: 'casual', 'smart_casual', 'formal', 'black_tie'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('smart_casual', 'Smart Casual'), ('business', 'Business'), ('cocktail', 'Cocktail'), ('formal', 'Formal'), ('black_tie', 'Black Tie'), ('white_tie', 'White Tie')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('tops', 'Верх (Tops/Shirts)'), ('layering', 'Другий шар (Layering/Tailoring)'), ('bottoms', 'Низ (Bottoms)'), ('onepiece', 'Суцільний одяг (One-piece/Sets)'), ('outerwear', 'Верхній одяг (Outerwear)'), ('footwear', 'Взуття (Footwear)'), ('accessory', 'Аксесуари (Accessories)')], max_length=20)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('smart_casual', 'Smart Casual'), ('business', 'Business'), ('cocktail', 'Cocktail'), ('formal', 'Formal'), ('black_tie', 'Black Tie')], max_length=20)),
                ('source_url', models.URLField(unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('pattern', models.CharField(choices=[('solid', 'Однотонний'), ('striped', 'Смугастий'), ('checked', 'Клітинка'), ('print', 'Принт'), ('floral', 'Квітковий'), ('abstract', 'Абстрактний')], default='solid', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Чоловіче'), ('F', 'Жіноче'), ('U', 'Унісекс')], default='U', max_length=10)),
                ('is_set', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('image_local', models.ImageField(blank=True, null=True, upload_to='clothing/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trapApp.brand')),
                ('events', models.ManyToManyField(blank=True, related_name='items', to='trapApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=10)),
                ('size_type', models.CharField(choices=[('alpha', 'Літерний (S/M/L)'), ('numeric', 'Числовий (36/38)')], default='alpha', max_length=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='trapApp.clothingitem')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='trapApp.event')),
                ('items', models.ManyToManyField(related_name='outfits', to='trapApp.clothingitem')),
            ],
        ),
    ]
