# Generated by Django 5.2.6 on 2026-02-21 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва події')),
                ('event_type', models.CharField(choices=[('wedding', 'Весілля'), ('party', 'Вечірка'), ('work', 'Робота/Офіс'), ('date', 'Побачення'), ('casual', 'Повсякденне'), ('sport', 'Спорт'), ('beach', 'Пляж'), ('formal', 'Офіційний захід')], max_length=50, verbose_name='Тип події')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('color', models.CharField(max_length=50, verbose_name='Колір')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, verbose_name='Розмір')),
                ('gender', models.CharField(choices=[('male', 'Чоловічий'), ('female', 'Жіночий'), ('unisex', 'Унісекс')], default='unisex', max_length=10, verbose_name='Стать')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('url', models.URLField(max_length=500, verbose_name='Посилання на товар')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Посилання на фото')),
                ('source_site', models.CharField(max_length=100, verbose_name='Джерело (сайт)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trapApp.category', verbose_name='Категорія')),
                ('suitable_for', models.ManyToManyField(blank=True, to='trapApp.event', verbose_name='Підходить для')),
            ],
            options={
                'verbose_name': 'Одяг',
                'verbose_name_plural': 'Одяг',
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва образу')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Збережений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trapApp.event', verbose_name='Подія')),
                ('items', models.ManyToManyField(to='trapApp.clothingitem', verbose_name='Речі в образі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Образи',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10, verbose_name='Розмір')),
                ('preferred_style', models.CharField(choices=[('casual', 'Повсякденний'), ('classic', 'Класичний'), ('sport', 'Спортивний'), ('elegant', 'Елегантний'), ('streetwear', 'Стріт')], max_length=20, verbose_name='Улюблений стиль')),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мінімальний бюджет')),
                ('budget_max', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Максимальний бюджет')),
                ('gender', models.CharField(choices=[('male', 'Чоловічий'), ('female', 'Жіночий'), ('unisex', 'Унісекс')], max_length=10, verbose_name='Стать')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
    ]
