# Generated by Django 5.2.6 on 2026-03-09 18:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField()),
                ('formality_range', models.CharField(help_text="Наприклад: 'casual', 'smart_casual', 'formal', 'black_tie'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('smart_casual', 'Smart Casual'), ('business', 'Business'), ('cocktail', 'Cocktail'), ('formal', 'Formal'), ('black_tie', 'Black Tie'), ('white_tie', 'White Tie')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('tops', 'Верх (Tops/Shirts)'), ('layering', 'Другий шар (Layering/Tailoring)'), ('bottoms', 'Низ (Bottoms)'), ('onepiece', 'Суцільний одяг (One-piece/Sets)'), ('outerwear', 'Верхній одяг (Outerwear)'), ('footwear', 'Взуття (Footwear)'), ('accessory', 'Аксесуари (Accessories)')], max_length=20)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('smart_casual', 'Smart Casual'), ('business', 'Business'), ('cocktail', 'Cocktail'), ('formal', 'Formal'), ('black_tie', 'Black Tie')], max_length=20)),
                ('source_url', models.URLField(unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('pattern', models.CharField(choices=[('solid', 'Однотонний'), ('striped', 'Смугастий'), ('checked', 'Клітинка'), ('print', 'Принт'), ('floral', 'Квітковий'), ('abstract', 'Абстрактний')], default='solid', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Чоловіче'), ('F', 'Жіноче'), ('U', 'Унісекс')], default='U', max_length=10)),
                ('is_set', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('image_local', models.ImageField(blank=True, null=True, upload_to='clothing/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trapApp.brand')),
                ('events', models.ManyToManyField(blank=True, related_name='items', to='trapApp.event')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=10)),
                ('size_type', models.CharField(choices=[('alpha', 'Літерний (S/M/L)'), ('numeric', 'Числовий (36/38)')], default='alpha', max_length=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='trapApp.clothingitem')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='trapApp.event')),
                ('items', models.ManyToManyField(related_name='outfits', to='trapApp.clothingitem')),
            ],
        ),
    ]
