# Generated by Django 5.2.6 on 2026-03-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='source_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
