# Generated by Django 5.2.6 on 2026-02-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0002_brand_color_dresscode_size_tag_remove_outfit_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWardrobeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='Session ID or User ID', max_length=255)),
                ('image', models.ImageField(upload_to='wardrobe_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('category_guess', models.CharField(blank=True, max_length=100)),
                ('style', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trapApp.event')),
                ('suggested_products', models.ManyToManyField(related_name='suggested_in_outfits', to='trapApp.product')),
                ('wardrobe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='trapApp.userwardrobeitem')),
            ],
        ),
    ]
