# Generated by Django 5.2.6 on 2026-04-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0004_brand_logo_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('tops', 'Верх'), ('layering', 'Другий шар'), ('bottoms', 'Низ'), ('onepiece', 'Суцільний одяг'), ('outerwear', 'Верхній одяг'), ('footwear', 'Взуття'), ('accessory', 'Аксесуари')], max_length=20),
        ),
    ]
