# Generated by Django 5.2.6 on 2026-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0005_alter_clothingitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('minimalism', 'Minimalism'), ('old_money', 'Old Money'), ('streetwear', 'Streetwear'), ('gorpcore', 'Gorpcore'), ('grunge', 'Grunge'), ('cyberpunk', 'Cyberpunk / Techwear'), ('vintage', 'Vintage / Retro'), ('dark_academia', 'Dark Academia'), ('avant_garde', 'Avant-Garde'), ('workwear', 'Workwear')], max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стилі',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'ordering': ['-scraped_at'], 'verbose_name': 'Одяг', 'verbose_name_plural': 'Одяг'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name'], 'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезони'},
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='subcategory',
            field=models.CharField(choices=[('t_shirt', 'Футболка'), ('shirt', 'Сорочка'), ('blouse', 'Блуза'), ('polo', 'Поло'), ('tank_top', 'Майка'), ('long_sleeve', 'Лонгслів'), ('crop_top', 'Кроп-топ'), ('blazer', 'Блейзер / Піджак'), ('cardigan', 'Кардиган'), ('sweater', 'Светр'), ('hoodie', 'Худі'), ('sweatshirt', 'Світшот'), ('vest', 'Жилет'), ('suit_set', 'Костюм (комплект)'), ('jeans', 'Джинси'), ('trousers', 'Штани'), ('linen_pants', 'Лляні штани'), ('shorts', 'Шорти'), ('skirt', 'Спідниця'), ('leggings', 'Легінси'), ('dress', 'Сукня'), ('sundress', 'Сарафан'), ('jumpsuit', 'Комбінезон'), ('swimsuit', 'Купальник'), ('bikini', 'Бікіні'), ('coat', 'Пальто'), ('wool_coat', 'Вовняне пальто'), ('trench', 'Тренч'), ('puffer', 'Пуховик'), ('quilted_jacket', 'Стьобана куртка'), ('leather_jacket', 'Шкіряна куртка'), ('denim_jacket', 'Джинсова куртка'), ('bomber', 'Бомбер'), ('parka', 'Парка'), ('fur_coat', 'Хутряна куртка'), ('sneakers', 'Кросівки'), ('boots', 'Черевики'), ('winter_boots', 'Зимові чоботи'), ('cowboy_boots', 'Ковбойські чоботи'), ('loafers', 'Лофери'), ('oxford_shoes', 'Оксфорди'), ('heels', 'Туфлі на підборах'), ('flats', 'Балетки'), ('sandals', 'Сандалі'), ('flip_flops', 'Шльопанці'), ('belt', 'Ремінь'), ('tie', 'Краватка'), ('scarf', 'Шарф / Хустка'), ('hat', 'Головний убір'), ('sunglasses', 'Окуляри'), ('jewelry', 'Прикраси'), ('earrings', 'Сережки'), ('bracelet', 'Браслет'), ('bag', 'Сумка'), ('tote', 'Шопер'), ('clutch', 'Клатч'), ('socks', 'Шкарпетки'), ('other_accessory', 'Інший аксесуар')], default='other_accessory', help_text="Конкретний тип одягу. Обов'язково заповнити (тагер або вручну).", max_length=30),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tag_source',
            field=models.CharField(choices=[('scraper', 'Скрепер'), ('manual', 'Вручну'), ('ml_v1', 'ML v1 (CLIP)'), ('rules', 'Правила'), ('mixed', 'CLIP + правила')], default='scraper', max_length=20),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='brand',
            name='formality_range',
            field=models.CharField(help_text="Наприклад: 'smart_casual', 'cocktail', 'black_tie'", max_length=50),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='formality',
            field=models.CharField(choices=[('white_tie', 'White Tie'), ('black_tie', 'Black Tie'), ('black_tie_creative', 'Black Tie Creative'), ('business_formal', 'Business Formal'), ('business_casual', 'Business Casual'), ('smart_casual', 'Smart Casual'), ('cocktail', 'Cocktail'), ('after_five', 'After Five (A5)'), ('festival_chic', 'Festival Chic'), ('semi_formal', 'Semi-Formal')], default='smart_casual', max_length=30),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='seasons',
            field=models.ManyToManyField(related_name='items', to='trapApp.season'),
        ),
        migrations.AlterField(
            model_name='event',
            name='formality',
            field=models.CharField(choices=[('white_tie', 'White Tie'), ('black_tie', 'Black Tie'), ('black_tie_creative', 'Black Tie Creative'), ('business_formal', 'Business Formal'), ('business_casual', 'Business Casual'), ('smart_casual', 'Smart Casual'), ('cocktail', 'Cocktail'), ('after_five', 'After Five (A5)'), ('festival_chic', 'Festival Chic'), ('semi_formal', 'Semi-Formal')], max_length=30),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='items', to='trapApp.style'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['gender', 'category'], name='trapApp_clo_gender_48eb44_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['category', 'subcategory'], name='trapApp_clo_categor_c4379a_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['formality', 'gender'], name='trapApp_clo_formali_76bfb6_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['brand', 'gender'], name='trapApp_clo_brand_i_95220d_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['price'], name='trapApp_clo_price_637f89_idx'),
        ),
    ]
