# Generated by Django 5.2.6 on 2026-04-25 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0006_style_alter_clothingitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('день народження', 'День народження'), ('ювілей', 'Ювілей'), ('заручини', 'Заручини'), ('розпис', 'Розпис'), ('весільний банкет (гість)', 'Весільний банкет (гість)'), ('коктейльна вечірка', 'Коктейльна вечірка'), ('формальний вечір', 'Формальний вечір'), ('корпоратив', 'Корпоратив'), ('конференція', 'Конференція'), ('нетворкінг', 'Нетворкінг'), ('презентація', 'Презентація'), ('публічний виступ', 'Публічний виступ'), ('фотосесія', 'Фотосесія'), ('випуск з університету', 'Випуск з університету'), ('театр', 'Театр'), ('опера / філармонія', 'Опера / філармонія'), ('гала-вечір', 'Гала-вечір'), ('благодійний бал', 'Благодійний бал'), ('свято в родині', 'Свято в родині'), ('бранч / зустріч з друзями', 'Бранч / зустріч з друзями')], max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Чоловічий'), ('female', 'Жіночий'), ('unisex', 'Унісекс')], default='unisex', max_length=10)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit_items', models.ManyToManyField(blank=True, related_name='notes', to='trapApp.clothingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Нотатка',
                'verbose_name_plural': 'Нотатки',
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
