# Generated by Django 5.2.6 on 2026-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0007_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mode',
            field=models.CharField(choices=[('auto', 'Автоматично'), ('manual', 'Вручну')], default='auto', max_length=10),
        ),
    ]
