# Generated by Django 5.2.6 on 2026-04-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0008_note_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='outfit_locked',
            field=models.BooleanField(default=False),
        ),
    ]
