# Generated by Django 5.2.6 on 2026-04-30 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0009_note_outfit_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('picker', 'Підбір образу'), ('wardrobe', 'Гардероб'), ('note', 'Захід')], default='picker', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wardrobe_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, related_name='saved_outfits', to='trapApp.clothingitem')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_outfits', to='trapApp.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Збережений образ',
                'verbose_name_plural': 'Збережені образи',
                'ordering': ['-created_at'],
            },
        ),
    ]
