# Generated by Django 6.0.2 on 2026-05-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapApp', '0013_order_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
